/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    News: typeof import('./src/components/News/index.vue')['default']
    Papercard: typeof import('./src/components/Publications/Papercard/index.vue')['default']
    People: typeof import('./src/components/People/index.vue')['default']
    Peoplecard: typeof import('./src/components/People/Peoplecard/index.vue')['default']
    Publications: typeof import('./src/components/Publications/index.vue')['default']
    RecentWork: typeof import('./src/components/Home/RecentWork/index.vue')['default']
    Research: typeof import('./src/components/Research/index.vue')['default']
    Researchcard: typeof import('./src/components/Research/Researchcard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
